name: Android CI

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'
        required: true
  pull_request:
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v4

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Quality - Spotless
        run: ./gradlew spotlessCheck

      - name: Quality - Detekt
        run: ./gradlew detekt

      - name: Quality - Lint
        run: ./gradlew lint

      - name: Quality - Dependency Guard
        run: ./gradlew dependencyGuard
        
      - name: 授予执行权限
        run: chmod +x gradlew
        
      - name: Build
        run: ./gradlew assembleRelease && cd app-k9mail/build/outputs/apk/release && ls
        
      - name: 上传APK
        uses: actions/upload-artifact@v3
        with:
          name: app-k9mail
          path: app-k9mail/build/outputs/apk/release/*/**
